name: Run the Test Suite

on:
    pull_request:

jobs:
    run-pytest:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4
              
            - name: build the test image
              run: docker build -t test_calculator .

            - name: run the test image
              run: docker run --rm test_calculator
